// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnosDesk.Api.Data;

#nullable disable

namespace TurnosDesk.Api_.Migrations
{
    [DbContext(typeof(TurnosDeskDbContext))]
    partial class TurnosDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.QueueTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CalledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("DailySequence")
                        .HasColumnType("int");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset?>("NoShowAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ServiceCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date");

                    b.Property<int?>("ServiceModuleId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ServiceStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("ServiceModuleId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("BranchId", "ServiceDate", "DailySequence")
                        .IsUnique();

                    b.HasIndex("BranchId", "ServiceDate", "Folio")
                        .IsUnique();

                    b.HasIndex("BranchId", "ServiceDate", "Status");

                    b.ToTable("QueueTickets", (string)null);
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "Code")
                        .IsUnique();

                    b.HasIndex("BranchId", "Name");

                    b.ToTable("ServiceAreas", (string)null);
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ServiceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Window");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAreaId");

                    b.HasIndex("BranchId", "Code")
                        .IsUnique();

                    b.HasIndex("BranchId", "Name");

                    b.ToTable("ServiceModules", (string)null);
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("EstimatedMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Normal");

                    b.Property<int?>("ServiceAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Active");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("ServiceAreaId");

                    b.ToTable("ServiceTypes", (string)null);
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.TicketEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("QueueTicketId")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceModuleId");

                    b.HasIndex("QueueTicketId", "CreatedAt");

                    b.ToTable("TicketEvents", (string)null);
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.QueueTicket", b =>
                {
                    b.HasOne("TurnosDesk.Api.Domain.Entities.Branch", "Branch")
                        .WithMany("QueueTickets")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosDesk.Api.Domain.Entities.ServiceModule", "ServiceModule")
                        .WithMany("QueueTickets")
                        .HasForeignKey("ServiceModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TurnosDesk.Api.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("QueueTickets")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ServiceModule");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceArea", b =>
                {
                    b.HasOne("TurnosDesk.Api.Domain.Entities.Branch", "Branch")
                        .WithMany("ServiceAreas")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceModule", b =>
                {
                    b.HasOne("TurnosDesk.Api.Domain.Entities.Branch", "Branch")
                        .WithMany("ServiceModules")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TurnosDesk.Api.Domain.Entities.ServiceArea", "ServiceArea")
                        .WithMany("ServiceModules")
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceType", b =>
                {
                    b.HasOne("TurnosDesk.Api.Domain.Entities.ServiceArea", "ServiceArea")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("ServiceAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceArea");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.TicketEvent", b =>
                {
                    b.HasOne("TurnosDesk.Api.Domain.Entities.QueueTicket", "QueueTicket")
                        .WithMany("Events")
                        .HasForeignKey("QueueTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TurnosDesk.Api.Domain.Entities.ServiceModule", "ServiceModule")
                        .WithMany("TicketEvents")
                        .HasForeignKey("ServiceModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QueueTicket");

                    b.Navigation("ServiceModule");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.Branch", b =>
                {
                    b.Navigation("QueueTickets");

                    b.Navigation("ServiceAreas");

                    b.Navigation("ServiceModules");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.QueueTicket", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceArea", b =>
                {
                    b.Navigation("ServiceModules");

                    b.Navigation("ServiceTypes");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceModule", b =>
                {
                    b.Navigation("QueueTickets");

                    b.Navigation("TicketEvents");
                });

            modelBuilder.Entity("TurnosDesk.Api.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("QueueTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
